# -*- coding: utf-8 -*-
"""Akram_Uddin_UFC_Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Rytl2wMYuvS_cPVRI2NAhN27B3d_fJQ
"""

!pip install streamlit

import pandas as pd
import streamlit as st

df = pd.read_csv("fighter_stats.csv")

df.head()

st.title("MMA Fighter Stats Dashboard")

fighter_name = st.selectbox("Select a fighter:", df['name'].sort_values())

fighter = df[df['name'] == fighter_name]

st.subheader(f"{fighter.iloc[0]['name']}'s Stats")
st.write(f"**Wins:** {fighter.iloc[0]['wins']}")
st.write(f"**Losses:** {fighter.iloc[0]['losses']}")
st.write(f"**Height (cm):** {fighter.iloc[0]['height']}")
st.write(f"**Weight (kg):** {fighter.iloc[0]['weight']}")